# Generated by Django 5.2.4 on 2025-08-23 18:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Enter a valid phone number including country code', max_length=13, null=True, unique=True, verbose_name='Phone Number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='nurse', max_length=100)),
                ('full_name', models.CharField(default='nurse', max_length=100)),
                ('contract_type', models.CharField(choices=[('official', 'Official'), ('insured', 'Insured')], max_length=20)),
                ('preferred_shifts', models.JSONField(blank=True, default=dict)),
                ('monthly_hours_required', models.PositiveIntegerField()),
                ('ward', models.CharField(default='OBGYN', max_length=50)),
                ('is_headnurse', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Morning Shift', max_length=200)),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='20:00')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='MORNING', max_length=10)),
                ('ward', models.CharField(default='OBGYN', max_length=50)),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='schedule.nurseprofile')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_shifts', to='schedule.nurseprofile')),
            ],
            options={
                'unique_together': {('date', 'shift_type', 'ward')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='MORNING', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.nurseprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.shift')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileSchedulingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(default='MORNING', max_length=50)),
                ('allow_post_night_off', models.BooleanField(default=True)),
                ('max_nurses_per_shift', models.PositiveIntegerField(default=3)),
                ('ward', models.CharField(default='OBGYN', max_length=50)),
                ('max_shifts_per_day', models.PositiveIntegerField(default=2)),
                ('max_shifts_per_week', models.PositiveIntegerField(default=5)),
                ('min_rest_hours_between_shifts', models.PositiveIntegerField(default=8)),
                ('allow_night_shifts', models.BooleanField(default=True)),
                ('head_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
