# Generated by Django 5.2.4 on 2025-07-25 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='nurse', max_length=100)),
                ('contract_type', models.CharField(choices=[('official', 'Official'), ('insured', 'Insured')], max_length=20)),
                ('preferred_shifts', models.JSONField(blank=True, default=dict)),
                ('monthly_hours_required', models.PositiveIntegerField()),
                ('ward', models.CharField(default='OBGYN', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(default='MORNING', max_length=50)),
                ('allow_post_night_off', models.BooleanField(default=True)),
                ('max_nurses_per_shift', models.JSONField(default=dict)),
                ('ward', models.CharField(default='OBGYN', max_length=50)),
                ('head_nurse', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='MORNING', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('nurse', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='schedule.nurseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default='8 AM')),
                ('end_time', models.DateTimeField(default='8 PM')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='MORNING', max_length=10)),
                ('ward', models.CharField(default='OBGYN', max_length=50)),
                ('assigned_nurse', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='schedule.nurseprofile')),
                ('nurse', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='requested_shifts', to='schedule.nurseprofile')),
            ],
            options={
                'unique_together': {('date', 'shift_type', 'ward')},
            },
        ),
    ]
